// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAdhesivoDian.Models;

#nullable disable

namespace WebAdhesivoDian.Migrations
{
    [DbContext(typeof(WebAdhesivoDianContext))]
    [Migration("20220404133516_InicioProyecto")]
    partial class InicioProyecto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAdhesivoDian.Models.Cajero", b =>
                {
                    b.Property<int>("IdCajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCajero"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdOficina")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OficinaIdOficina")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ultimaNumeracion")
                        .HasColumnType("int");

                    b.HasKey("IdCajero");

                    b.HasIndex("OficinaIdOficina");

                    b.ToTable("Cajero");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsecutivoCadena")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("FormateoCodigoFijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaBaseSalida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UltimoPedido")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.DetalleEncabezado", b =>
                {
                    b.Property<int>("IdDetalleEncabezado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleEncabezado"), 1L, 1);

                    b.Property<int?>("CajeroIdCajero")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFinal")
                        .HasColumnType("int");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int");

                    b.Property<int>("ConsectivoFinalCadena")
                        .HasColumnType("int");

                    b.Property<int>("ConsectivoinicialCadena")
                        .HasColumnType("int");

                    b.Property<int?>("EncabezadoIdEncabezado")
                        .HasColumnType("int");

                    b.Property<int>("IdCajero")
                        .HasColumnType("int");

                    b.Property<int>("IdEncabezado")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleEncabezado");

                    b.HasIndex("CajeroIdCajero");

                    b.HasIndex("EncabezadoIdEncabezado");

                    b.ToTable("DetalleEncabezado");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Encabezado", b =>
                {
                    b.Property<int>("IdEncabezado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEncabezado"), 1L, 1);

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivoCargado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEncabezado");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Encabezado");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Oficina", b =>
                {
                    b.Property<int>("IdOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOficina"), 1L, 1);

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoCiudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMunucio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponsable1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponsable2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponsable3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.HasKey("IdOficina");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Oficina");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Cajero", b =>
                {
                    b.HasOne("WebAdhesivoDian.Models.Oficina", "Oficina")
                        .WithMany("Cajeros")
                        .HasForeignKey("OficinaIdOficina");

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.DetalleEncabezado", b =>
                {
                    b.HasOne("WebAdhesivoDian.Models.Cajero", "Cajero")
                        .WithMany()
                        .HasForeignKey("CajeroIdCajero");

                    b.HasOne("WebAdhesivoDian.Models.Encabezado", "Encabezado")
                        .WithMany("DetalleEncabezados")
                        .HasForeignKey("EncabezadoIdEncabezado");

                    b.Navigation("Cajero");

                    b.Navigation("Encabezado");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Encabezado", b =>
                {
                    b.HasOne("WebAdhesivoDian.Models.Cliente", "Cliente")
                        .WithMany("Encabezados")
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Oficina", b =>
                {
                    b.HasOne("WebAdhesivoDian.Models.Cliente", "Cliente")
                        .WithMany("Oficinas")
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Cliente", b =>
                {
                    b.Navigation("Encabezados");

                    b.Navigation("Oficinas");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Encabezado", b =>
                {
                    b.Navigation("DetalleEncabezados");
                });

            modelBuilder.Entity("WebAdhesivoDian.Models.Oficina", b =>
                {
                    b.Navigation("Cajeros");
                });
#pragma warning restore 612, 618
        }
    }
}
